apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - image: justinwatkinson/demo-nginx:v2.0
        name: nginx-frontend
        ports:
        - containerPort: 80
